# fly.toml file generated for duck-or-cat on 2023-04-16T22:45:53+02:00

app = "duck-or-cat"
primary_region = "cdg"

[env]
  FLASK_APP="main flask run"

[http_service]
  internal_port = 8080
  force_https = true

[checks]
  [checks.alive]
    type = "tcp"
    interval = "15s"
    timeout = "2s"
    grace_period = "5s"
