# fly.toml file generated for duck-or-cat on 2023-04-17T14:52:52+02:00

app = "duck-or-cat"
primary_region = "cdg"

[http_service]
  internal_port = 5333
  force_https = true

[checks]
  [checks.alive]
    type = "tcp"
    interval = "15s"
    timeout = "2s"
    grace_period = "5s"
